### ISSUE TITLE
Iframe support

### ISSUE THREAD

**Issue by TheRealGWJosh** [Sainan/Set-Discord-Activity#17]
give the extension iframe support

**Comment by Sainan** [comment]
Please elaborate

**Comment by TheRealGWJosh** [comment]
so you know some pages have iframes and stuff well I use discord that way and the extension doesn't work so maybe add something that detects when someone is using discord in an iframe

**Comment by TheRealGWJosh** [comment]
![image](https://user-images.githubusercontent.com/68560159/110030864-10720a00-7ceb-11eb-9bfd-8c8493336c64.png) 
![image](https://user-images.githubusercontent.com/68560159/110031048-47e0b680-7ceb-11eb-8c26-0d395c666242.png)

in this window, discord is running in an iframe and the app doesn't respond

**Comment by Sainan** [comment]
That isn't Discord, it's some third-party service pretending to be Discord.

**Comment by TheRealGWJosh** [comment]
Nah it's a custom theme

**Comment by TheRealGWJosh** [comment]
I'm using stylus to theme discord and using tampermonkey to unblock discord from my school

**Comment by TheRealGWJosh** [comment]
![image](https://user-images.githubusercontent.com/68560159/110091422-46e07100-7d4d-11eb-9163-7c5bdb6b6be3.png)
![image](https://user-images.githubusercontent.com/68560159/110091480-552e8d00-7d4d-11eb-9ffd-dffda0387865.png)
![image](https://user-images.githubusercontent.com/68560159/110091532-64153f80-7d4d-11eb-8983-50b341379129.png)
![image](https://user-images.githubusercontent.com/68560159/110091599-78f1d300-7d4d-11eb-8568-a2ebb39c6d0a.png)

**Comment by TheRealGWJosh** [comment]
![image](https://user-images.githubusercontent.com/68560159/110091671-8f982a00-7d4d-11eb-99b4-0a91a4e981fc.png)
what it normally does without the userscript

**Comment by Sainan** [comment]
I see, that kind of confused me, but I assumed this would already work in an iframe.

**Comment by Sainan** [comment]
Well, it's literally impossible to have discord.com in an iframe.

![image](https://user-images.githubusercontent.com/63328889/110101385-bf721c80-7da3-11eb-811b-e564972defe9.png)

And I don't know what exactly is going on behind the scenes with your blocking & unblocking... stuff.

**Comment by TheRealGWJosh** [comment]
yeah I'm using another extension xD https://chrome.google.com/webstore/detail/iframe-allow/gifgpciglhhpmeefjdmlpboipkibhbjg

**Comment by TheRealGWJosh** [comment]
![image](https://user-images.githubusercontent.com/68560159/110102047-25858200-7d59-11eb-86ff-ab813da642f3.png)

**Comment by TheRealGWJosh** [comment]
well, thanks for listening :)

**Comment by Sainan** [comment]
Correction: It won't work in Chrome 90.

**Comment by TheRealGWJosh** [comment]
mmmmmmmmmmmmmmmmmmmmm yeah i'm using chrome 86 on my chromebook
![image](https://user-images.githubusercontent.com/68560159/110102757-0509f780-7d5a-11eb-966e-d4199d4e1ee1.png)
