### ISSUE TITLE
Publish as Firefox Addon

### ISSUE THREAD

**Issue by Wuelle** [Sainan/Set-Discord-Activity#18]
According to [https://www.extensiontest.com/](https://www.extensiontest.com/), the Chrome extension is fully compatible with Firefox, i don't see a reason not to publish it as a Firefox Addon as well.
(I am assuming that you haven't already done this since [README.md](https://github.com/Sainan/Set-Discord-Activity/blob/master/README.md) only contains a link to the Chrome extension and i can't find it for Firefox)

**Comment by Sainan** [comment]
Cool. I had actually tried it on Firefox and it didn't work.

**Comment by Wuelle** [comment]
Huh. I assumed that this extensiontest website worked since it was linked by some Mozilla Blog, but now that i actually look at the Code it can't possibly work in Firefox because `chrome.storage` and `chrome.runtime` is used. Nevermind then.

**Comment by Wuelle** [comment]
Though that's not actually the problem. Firefox simply doesn't support [the `persistent` parameter in manifest.json](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/background)

**Comment by brianclinkenbeard** [comment]
I believe the issue with Firefox is this: https://bugzilla.mozilla.org/show_bug.cgi?id=1267027
