### ISSUE TITLE
Animated Status

### ISSUE THREAD

**Issue by KolpixTV** [Sainan/Set-Discord-Activity#25]
Hey,

it would be nice if you can add a Animated Status ,so the Discord Status changes automatically every few seconds/minutes/hours.

**Comment by apenasigordev** [comment]
This is not allowed by the platform

**Comment by Sainan** [comment]
> This is not allowed by the platform
Well, this goes for this entire project, so xD

**Comment by Gurrman375** [comment]
Animated status?

**Comment by KolpixTV** [comment]
yes like betterdiscord

**Comment by Gurrman375** [comment]
So like this: https://youtu.be/64VZCQ2tu30

Isn't this project about rich presence and not custom status. Also entering your token is never really a safe option.
