### ISSUE TITLE
[question]

### ISSUE THREAD

**Issue by apenasigordev** [Sainan/Set-Discord-Activity#27]
I have a doubt, I was seeing the information and the languages ​​I saw, it was just "English" and "Deutsch".
![Screenshot_20210606-113639_Chrome](https://user-images.githubusercontent.com/80823011/120928719-39c07e80-c6bc-11eb-8c3d-6f8e76e86edf.jpg)
And there's Portuguese and Japanese too

**Comment by Sainan** [comment]
Japanese should now be available with the 2.10.0 update, although with Portuguese it might be missing a region specifier.

**Comment by apenasigordev** [comment]
okeh
