### ISSUE TITLE
Special Status messages like "Listening to Spotify"

### ISSUE THREAD

**Issue by XENONFFM** [Sainan/Set-Discord-Activity#9]
Hello Sainan

Could you explain shortly in which way your extension access the Discord Api?
Because with the normal way to access the Discord Api its not possible to make use of these "special" statuses.
Your code is the only one that allows this, I would be very grateful if you could help me understand what you are doing to achieve this!

Kind regards
Xenonffm

**Comment by Sainan** [comment]
Websocket hook.

And Discord already supports Spotify natively.
